// Code generated by mockery v2.43.2. DO NOT EDIT.

package converter

import (
	image "image"

	mock "github.com/stretchr/testify/mock"
)

// imageWriterMock is an autogenerated mock type for the imageWriter type
type imageWriterMock struct {
	mock.Mock
}

// Write provides a mock function with given fields: img, path, format
func (_m *imageWriterMock) Write(img image.Image, path string, format string) error {
	ret := _m.Called(img, path, format)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(image.Image, string, string) error); ok {
		r0 = rf(img, path, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newImageWriterMock creates a new instance of imageWriterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newImageWriterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *imageWriterMock {
	mock := &imageWriterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
